### ISSUE TITLE
Each command removes games for my game list.

### ISSUE THREAD

**Issue by MattMan76** [elierodrigue/Hakchi_HelpingHand#4]
I love the idea of this tool.  For some reason it removes games from my list. Does this tool remove the games from Hakchi2 when it makes changes to the names or something?

**Comment by Tyson716** [comment]
I'm having the same issue. Compressing NES roms in my list removes them all.

**Comment by elierodrigue** [comment]
which version of Hackchi are you using it with?

**Comment by MattMan76** [comment]
I have only tested it with 2.16.

**Comment by Tyson716** [comment]
Same here.

**Comment by elierodrigue** [comment]
i have not tested it with 2.16... can you give it a try with 2.14 to see if you have the same issue?

**Comment by ghost** [comment]
Same for me. Wanted to try the new "5 - Apply cache clearing fix", so I created a build and thought I'd try the compress game option. At first, the games are there, I went into the first folder and can verify my one uncompressed nes file was compressed. Not sure the time frame it happens (it's within several seconds), but when I either attempt to sync the games to my NESC or exit Hakchi2 and reopen it, the games are gone. I would get an error message when I tried to sync, probably because Hakchi2 thinks the games are there, when they're actually gone.

I tried this with the current build of Hakchi Helping Hand and version 1.1, (the latest release) on both Hakchi2 2.14b and 2.16c. It was an issue every time.

**Comment by elierodrigue** [comment]
I'll be changing the way it works pretty soon, it should fix those issues.

**Comment by elierodrigue** [comment]
Just fixed it in 1.2
